[package]
name = "motlie"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Main binary for motlie"

[dependencies]
